In [43]:
from sklearn import model_selection
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import pandas as pd
import numpy as np
df=pd.read_csv("dirty_iris.csv")
df

sepal length  sepal width  petal length  petal width           class  \
0             5.1          3.5           1.4          0.2     Iris-setosa   
1             5.1          3.0           1.4          0.2     Iris-setosa   
2             5.1          3.2           1.3          0.2     Iris-setosa   
3             5.1          3.1           1.5          0.2     Iris-setosa   
4             5.1          3.6           1.4          0.2     Iris-setosa   
..            ...          ...           ...          ...             ...   
145           6.7          3.0           5.2          2.3  Iris-virginica   
146           6.3          2.5           5.0          1.9  Iris-virginica   
147           6.5          3.0           5.2          2.0  Iris-virginica   
148           6.2          3.4           5.4          2.3  Iris-virginica   
149           5.9          3.0           5.1          1.8  Iris-virginica   

     Unnamed: 5  
0           NaN  
1           NaN  
2           NaN  
3           NaN  
4           NaN  
..          ...  
145         NaN  
146         NaN  
147         NaN  
148         NaN  
149         NaN  

[150 rows x 6 columns]

In [65]:
X=data[:,0:-2]
Y=data[:,-2]
data=df.values


In [66]:

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=3)

DTclassifer = DecisionTreeClassifier()
DTclassifer.fit(X_train,Y_train)
predictions=DTclassifer.predict(X_test)
predictions

In [67]:
dtree = DecisionTreeClassifier()

In [68]:
dtree.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [70]:
predictions = dtree.predict(X_test)

In [71]:
print("Accuracy using Random Subsampling : ", accuracy_score(Y_test,predictions))

Accuracy using Random Subsampling :  0.8888888888888888


In [72]:
print("Confusion Matrix  : \n\n", confusion_matrix(Y_test,predictions))

Confusion Matrix  : 

 [[17  0  0]
 [ 0 10  4]
 [ 0  1 13]]


In [73]:
print("Classification Report : \n\n", classification_report(Y_test,predictions))


Classification Report : 

                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        17
Iris-versicolor       0.91      0.71      0.80        14
 Iris-virginica       0.76      0.93      0.84        14

       accuracy                           0.89        45
      macro avg       0.89      0.88      0.88        45
   weighted avg       0.90      0.89      0.89        45



In [74]:
eval = 'accuracy'
model=DecisionTreeClassifier()
kfold = model_selection.KFold(n_splits=5, shuffle= True, random_state= 4)
results = model_selection.cross_val_score(model, X, Y, cv= kfold, scoring= eval)
print("Accuracy using Cross Validation : ",results.mean())

Accuracy using Cross Validation :  0.9533333333333334


In [76]:
classifier = KNeighborsClassifier()
classifier.fit(X_train,Y_train)
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

predictions = classifier.predict(X_test)
print("Accuracy using K-Neighbours classifier : ",accuracy_score(Y_test,predictions))

print("Confusion Matrix : \n\n",confusion_matrix(Y_test,predictions))

print("Classification Report : \n\n",classification_report(Y_test, predictions))

Accuracy using K-Neighbours classifier :  0.9555555555555556
Confusion Matrix : 

 [[17  0  0]
 [ 0 12  2]
 [ 0  0 14]]
Classification Report : 

                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        17
Iris-versicolor       1.00      0.86      0.92        14
 Iris-virginica       0.88      1.00      0.93        14

       accuracy                           0.96        45
      macro avg       0.96      0.95      0.95        45
   weighted avg       0.96      0.96      0.96        45



In [77]:
eval = 'accuracy'
model= KNeighborsClassifier()
kfold = model_selection.KFold(n_splits=5, shuffle= True, random_state=4)
results = model_selection.cross_val_score(model, X, Y, cv= kfold, scoring= eval)
print("Accuracy using Cross Validation : ",results.mean())

Accuracy using Cross Validation :  0.9666666666666668


In [78]:
models = []

models.append(('KNN',KNeighborsClassifier()))
models.append(('CART',DecisionTreeClassifier()))

scoring='accuracy'

results = []

for name, model in models:
    kfold = model_selection.KFold(n_splits=5, shuffle= True, random_state= 4)
    algo_result = model_selection.cross_val_score(model, X, Y, cv= kfold, scoring= eval)
    results.append(algo_result)
    str = "%s : %f" % (name, algo_result.mean())
    print(str)

KNN : 0.966667
CART : 0.946667
